watcher_watch_homepage:
    pattern:  /
    defaults: { _controller: WatcherWatchBundle:Default:index }

watcher_vote:
    pattern:  /vote/{id}
    defaults: { _controller: WatcherWatchBundle:Default:vote }
